Imporved OverloadEvent initialization and energy calculation logic
SINTEF-Power-system-asset-management/flexible_load_analysis pull request #21
Opened 2024-07-03 13:58 UTC by sheikhbil

(1) Added optional parameters to the OverloadEvent constructor.
(2) Updated the logic for calculating fl_surplus_energy_MWh to account for non-uniform timestamp widths and base case set to uniform timestamp widths.
(3) Kept the logic for calculating fl_rms_load using the for-loop method.
(4)Added checks for missing all_timestamp_widths when equal_timestamp_spacing is set to False.
(5)Updated the calculation of self.percentage_overload to handle cases where fl_power_limit is zero.

2024-07-03 14:36 UTC, danielbjerk requested changes
Looks great! Will be approved if feedback is addressed

2024-07-03 14:36 UTC, danielbjerk commented on flexible_load_analysis/flexibility/flexibility_need.py
>              fl_rms_load += ts_overload_event[i - 1, 1] * fl_dur
The calculation of RMS load should be done at the same place as the calculation of energy-above-capacity, just without subtracting the power limit.

2024-07-03 15:08 UTC, sheikhbil commented on flexible_load_analysis/flexibility/flexibility_need.py
>              fl_rms_load += ts_overload_event[i - 1, 1] * fl_dur
I have made the requested changes and addressed the review comments:
- Integrated the `fl_rms_load` calculation with the energy calculation loop.
- Ensured that `fl_rms_load` is calculated without subtracting the power limit.

Please review the updated code. Thank you!

2024-07-04 06:33 UTC, danielbjerk approved these changes

2024-07-04 06:34 UTC, merged